# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: [ sefl-hosted]

    steps:
    - uses: actions/checkout@v4
    - name: Verify Python & Databricks CLI version
      run: |
      python3 --version
      python --version
      
    - name: My test
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        python GHA.py
      env:
        gha_secrect: ${{secrets.GHA}}

